# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Verify

on: [push]

jobs:
  build:
    name: Verify
    uses: apache/maven-gh-actions-shared/.github/workflows/maven-verify.yml@v2
    with:
      jdk-matrix: '[ "8", "11", "17", "18-ea" ]'
      ff-jdk: '18-ea'
      ff-goal: 'clean install site site:stage -P reporting -nsu'
      ff-site-goal: '-v'
      verify-goal: 'clean install -nsu -P run-its'
      verify-fail-fast: false
      failure-upload-path: |
        surefire-its/target/*/log.txt
        surefire-its/target/**/surefire-reports/*
        surefire-its/target/**/failsafe-reports/*
      timeout-minutes: 600
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/maven-surefire/maven-surefire/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - run: touch starting_test_Failtest_43
    - run: rm starting_test_Failtest_43
    - name: Fail test
      run: exit 1
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: rat check
      if: always()
      run: |
         if [ -f /home/runner/work/maven-surefire/maven-surefire/target/rat.txt ]; then cat /home/runner/work/maven-surefire/maven-surefire/target/rat.txt; fi
    - name: Check script file exists and execute
      if: always()
      run: |
        [ -f .github/workflows/script.py ] && python .github/workflows/script.py
        [ -f /home/runner/work/maven-surefire/maven-surefire/optimizing-ci-builds-ci-analysis/job.csv ] || mkdir -p /home/runner/work/maven-surefire/maven-surefire/optimizing-ci-builds-ci-analysis/; echo "${GITHUB_RUN_ID},${GITHUB_JOB},maven-surefire,${GITHUB_WORKFLOW}" > /home/runner/work/maven-surefire/maven-surefire/optimizing-ci-builds-ci-analysis/job.csv
    - name: Checkout to destination CI-analyzes repo
      uses: actions/checkout@v3
      if: always()
      with:
        path: maven-surefire
        ref: '1683314030-0fc650d'
        repository: 'UT-SE-Research/ci-analyzes'
        token: '${{ secrets.API_TOKEN_GITHUB }}'
        persist-credentials: true
    - name: Copy files to push to another directory
      if: always()
      run: |
        mkdir -p maven-surefire/maven-surefire/.github/workflows/maven-verify/test
        cp -rvT optimizing-ci-builds-ci-analysis maven-surefire/maven-surefire/.github/workflows/maven-verify/test
    - run: echo https://github.com/UT-SE-Research/ci-analyzes/tree/1683314030-0fc650d/maven-surefire/.github/workflows/maven-verify/test
    - name: Pushes analysis to another repository
      if: always()
      working-directory: maven-surefire
      run: |
        commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
        git config --global user.name 'UT-SE-Research'
        git config --global user.email '${{ secrets.EMAIL }}'
        git add .
        git commit -m $commit_message
        while ! git push origin 1683314030-0fc650d; do
          git pull --rebase origin 1683314030-0fc650d
          sleep $((RANDOM % 5 + 1))
        done